import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

export const AgletSans = localFont({
  src: [
    {
      path: "../assets/fonts/Aglet_Sans/Aglet_Sans.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Aglet_Sans/Aglet_Sans_Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../assets/fonts/Aglet_Sans/Aglet_Sans_Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/Aglet_Sans/Aglet_Sans_Bold_Italic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  display: "auto",
  variable: "--font-aglet-sans",
});

export const metadata: Metadata = {
  title: "Pigmo - Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${AgletSans.className}`}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
